

format = "[$character]($character.style)[$directory]($directory.style)[$git_branch]($git_branch.style)[\\$](#8aadf4) "

[line_break]
disabled = true

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[➜ 󰄛](bold red)"


[git_branch]
format = "$symbol[\\(](#ca9ee6)[$branch]($style)[\\)](#ca9ee6)"
style = "red"
symbol = "[git:](#ca9ee6)"
